<html>
<head>
<meta charset="<?php bloginfo( 'charset' ); ?>" />
<title>Enter verification code</title>

<style>
body {
    color: #000000;
}
body {
    font-family: arial,sans-serif;
}
.body {
    margin: 0;
}
div.text {
    padding-bottom: 1em;
    padding-right: 1em;
}
div.error {
    color: red;
    padding-right: 1em;
}
.smaller {
    font-size: smaller;
}
#pinlabel {
    font-size: 0.8em;
    font-weight: bold;
}
#persistent-container {
    padding-left: 75px;
}
.padded {
    margin-top: 3px;
}
</style>
<?php wp_print_scripts('jquery');?>
<script type="text/javascript">
    function emailCode(){
        jQuery('#type').val('email');
        jQuery("#smsUserPin").val('');
        jQuery("#action").val('send-email');
        jQuery('#verify-form').submit();
        return false;
    }
    function cancel(){
        jQuery("#action").val('cancel');
        jQuery('#verify-form').submit();
        return false;
    }
</script>
</head>
<body>
<div class="body">
  <form name="verifyForm" method="post" action="" id="verify-form">
  <input type="hidden" name="wp2sv_nonce" value="<?php echo wp_create_nonce('wp2sv_nonce');?>"/>
  <input type="hidden" name="wp2sv_type" id="type" value="<?php echo $this->get_receive_method();?>"/>
  <input type="hidden" name="wp2sv_action" id="action" value="check-code"/>
  <br/>
  <div class="text smaller" id="verifyText">
  <?php if($this->get_receive_method()=='mobile')
            _e('Enter the verification code generated by your mobile application.','wp2sv');
        else
            printf(__('Enter the verification code sent to your email ending in %s.','wp2sv'),$this->get_email_ending());
  ?>
  </div>
  <div id="verify">
  <div>
  <label for="smsUserPin" id="pinlabel">
  Enter code:
  </label>
  <input type="text" title="Verification codes contain only numbers." pattern="[0-9 ]*" dir="ltr" autocomplete="off" size="6" value="" id="smsUserPin" name="wp2sv_code">
  <input type="submit" class="sa-button" value="Verify" id="smsVerifyPin" name="smsVerifyPin">
  </div>
  <?php if($this->error_message):?>
  <div class="error smaller" id="error">
    <?php echo $this->error_message;?>
  </div>
  <?php endif;?>
  
  <div class="padded" id="persistent-container">
  <input type="checkbox"<?php checked(true,$this->wp2sv_user_fav_trusted())?> value="yes" id="PersistentCookie" name="wp2sv_remember">
  <label for="PersistentCookie" class="smaller">
  Remember this computer for 30 days.
  
  </label>
  </div>
  <br/>
  <?php if($this->has_email()):?>
      <div class="padded smaller" id="didnotreceive">
      <a href="javascript:emailCode()">
      <?php if($this->get_receive_method()=='email'):?>
            Didn't receive email? - Send code again
      <?php else:?>
            Don't have your phone? - Send code to your email
      <?php endif;?>
      </a></div>
  <?php endif;?>
  <div class="padded smaller" id="cancelLink">
  <a href="javascript:cancel()">Cancel</a>
  </div>
  </div>
  </form>
  <div id="filter" style="display: none;"></div>
  <div style="clear:both"></div>
  </div>
</body>
</html>